GoogleCloudPlatform/runtimes-common

- check_if_image_tag_exists/README.md
> Add documentation for using intermediate cloudbuild step

- check_if_image_tag_exists/main.py
> Add flag to force build even if tag exists in remote repository (for testing)

- .travis.yml
We don't have any bash scripts yet, but it'll be good to get this in before we do.
> Add shellcheck to travis.

- structure_tests/structure_test.go
one of the main motivations behind supported regexes for testing command output/file contents is to make sure things are **not** there; this is usually accomplished through regex lookaround, but unfortunately golang does not support this. to workaround this, add `excluded` fields to the test JSON to explicitly specify which should not exist in the output/contents during tests.
@dlorenc @selgamal
> add excluded (alongside expected) json fields to workaround golang's lack of regex lookaround

- .gitignore
- check_if_image_tag_exists/build.sh
- check_if_image_tag_exists/cloudbuild.yaml.in
https://github.com/GoogleCloudPlatform/runtimes-common/issues/9
@dlorenc
> use envsubst over sed when building tag check image

- structure_tests/README.md
> add structure test documentation

- Godeps/Godeps.json
- Godeps/Readme
- check_if_image_tag_exists/structure_test.json
- check_if_image_tag_exists/structure_test.yaml
- structure_tests/structure_test.go
- vendor/github.com/ghodss/yaml/.gitignore
- vendor/github.com/ghodss/yaml/.travis.yml
- vendor/github.com/ghodss/yaml/LICENSE
- vendor/github.com/ghodss/yaml/README.md
- vendor/github.com/ghodss/yaml/fields.go
- vendor/github.com/ghodss/yaml/yaml.go
- vendor/gopkg.in/yaml.v2/LICENSE
- vendor/gopkg.in/yaml.v2/LICENSE.libyaml
- vendor/gopkg.in/yaml.v2/README.md
- vendor/gopkg.in/yaml.v2/apic.go
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/parserc.go
- vendor/gopkg.in/yaml.v2/readerc.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/sorter.go
- vendor/gopkg.in/yaml.v2/writerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
- vendor/gopkg.in/yaml.v2/yamlprivateh.go
cc @nkubala 
This also starts us using Godeps for dependency management.
> Add yaml support.

- structure_tests/README.md
> Update docs with YAML files as well.

- .gitignore
- .travis.yml
- reconciletags/config_integrity_test.py
> adding tests for testing json config structure

- reconciletags/reconciletags_e2e_test.py
- reconciletags/tiny_docker_image/Dockerfile
> Tag Reconciler end to end test

- structure_tests/README.md
> Update docs on how to fetch the standalone script.

- reconciletags/config_integrity_test.py
- reconciletags/reconciletags.py
- reconciletags/reconciletags_e2e_test.py
- reconciletags/reconciletags_test.py
- reconciletags/sample.json
> fixing reconciler to handle multiple registries properly

- reconciletags/data_integrity_test.py
> adding tests for data consistency

- .gofmt.sh
- check_if_image_tag_exists/Dockerfile
- check_if_image_tag_exists/build.sh
- check_if_image_tag_exists/main.py
- reconciletags/config_integrity_test.py
- reconciletags/reconciletags.py
- reconciletags/reconciletags_e2e_test.py
- reconciletags/reconciletags_test.py
- reconciletags/tiny_docker_image/Dockerfile
- structure_tests/Dockerfile
- structure_tests/build.sh
- structure_tests/command_test_v1.go
- structure_tests/ext_run.sh
- structure_tests/file_content_test_v1.go
- structure_tests/file_existence_test_v1.go
- structure_tests/run.sh
- structure_tests/structure_test.go
- structure_tests/structure_test_v1.go
- structure_tests/types.go
> add Apache 2.0 license headers to all applicable files

- structure_tests/ext_run.sh
> use proper file extension when copying config files

- .travis.yml
- requirements.txt
> adding requirements.txt

- check_if_image_tag_exists/structure_test.yaml
- check_if_image_tag_exists/test_config.json
- structure_tests/structure_test.go
- structure_tests/structure_test_v1.go
- structure_tests/types.go
otherwise, log the number of tests run. also fixes configs for tag checker image. fixes #58 
@dlorenc
> error structure test run if no tests are run

- structure_tests/build.sh
- structure_tests/tests/.gitignore
- structure_tests/tests/cloudbuild.yaml.in
- structure_tests/tests/debian_failure_test.json
- structure_tests/tests/debian_test.json
- structure_tests/tests/structure_test_test.json
- structure_tests/tests/structure_test_tests.sh
@dlorenc @nkubala 
Addresses #10
> adding tests for the structure test image

- structure_tests/ext_run.sh
Uses bash arrays to get the quoting right, which requires switching
from /bin/sh to /bin/bash.
Fixes #69
> Handle spaces in the current working directory.

- structure_tests/README.md
- structure_tests/licenses_test.go
- structure_tests/structure_test_v1.go
- structure_tests/tests/debian_test.json
- structure_tests/tests/structure_test_test.json
> adding test to check for proper licenses

- structure_tests/README.md
- structure_tests/file_existence_test_v1.go
- structure_tests/structure_test_v1.go
- structure_tests/tests/debian_failure_test.json
- structure_tests/tests/debian_test.json
> adding permissions check to file existence tests

- security_check/main.py
Note that this will require upgrading the version of gcloud we're using in our CI system.
@dlorenc @nkubala
> take base image vulnerabilities into account for security tests

- security_check/main.py
> removing finding latest digest and adding logging

- integration_tests/build.sh
- integration_tests/cloudbuild.yaml.in
- integration_tests/structure_test.yaml
add a build script and a cloudbuild.yaml for building in container build. add basic structure test config.
> add build artifacts for cloudbuild

- integration_tests/requirements.txt
- integration_tests/testsuite/deploy_app.py
- integration_tests/testsuite/driver.py
- integration_tests/testsuite/test_exception.py
- integration_tests/testsuite/test_logging.py
- integration_tests/testsuite/test_monitoring.py
- integration_tests/testsuite/test_root.py
- integration_tests/testsuite/test_util.py
* updated license headers
* renamed parameters for skipping tests for clarity
* made various utility methods public where appropriate
* prefer `self.assertEquals`/`self.assertTrue` over `self.fail`
* pythonize and clean driver logic
@dlorenc @tejal29
> various formatting and syntax improvements

- reconciletags/config_integrity_test.py
> update missed test config directory

- runtime_builders/publish_builders.py
- runtime_builders/template_builder.py
- structure_tests/cloudbuild.yaml.in
> add script to publish list of builders uploaded to GCS

- runtime_builders/data_integrity.py
- runtime_builders/publish_builders.py
- runtime_builders/template_builder.py
> add script to verify integrity of runtime builder config files in GCS

- check_if_image_tag_exists/cloudbuild.yaml.in
- runtime_builders/template_builder.py
> add explicit tags to cloudbuild.yaml. log file name when templating

- security_check/main.py
> add license header to security check script

- runtime_builders/publish_builders.py
> fix substring when publishing latest version

- runtime_builders/publish_builders.py
> strip yaml extension from latest file path when publishing

- runtime_builders/data_integrity.py
> add .yaml extension to version latest file. fix logging

- runtime_builders/template_builder.py
> template all images provided as build step arguments in cloudbuild config

- runtime_builders/template_builder.py
> use std regex module

- integration_tests/README.md
> clarify Dockerfile templating in integration test docs

- check_if_image_tag_exists/build.sh
- sample_image/Dockerfile
- sample_image/build.sh
- sample_image/cloudbuild.yaml.in
I'll remove the builder configs for the structure test and tag check images once this is merged.
@dlorenc
> add sample image for demoing builder templating/publishing

- security_check/main.py
The output now looks like:
Vulnerability found.
CVE: providers/goog-vulnz/notes/CVE-2016-6252
SEVERITY: MEDIUM
PACKAGES: shadow (1:4.2-3+deb8u1)
FIXED PACKAGES: shadow (1:4.2-3+deb8u3)
> Make vuln output more copy-pasteable.

- integration_tests/Dockerfile
> pin to specific gcloud version to avoid using gcloud update

- integration_tests/README.md
> update docs to specify Dockerfile.in

- docgen/lib/proto/docgen.proto
- docgen/lib/render/enhanced.go
- docgen/lib/render/templates/README.md.tmpl
Copy instruction allows copying files from or to containers.
> Add copy instruction

- versioning/scripts/cloudbuild/main.go
Also include various minor improvements to the formatting of yaml output.
> Add support for functional_tests

- BUILD
> Add LICENSE stanza to BUILD file.

- versioning/scripts/dockerfiles/main.go
It may be useful to verify dockerfiles.
> Add verify flag to dockerfiles

- runtime_builders/template_builder.py
> adjust regex to ignore leading characters in image paths

- versioning/scripts/dockerfiles/main.go
- Add summary
- Add undefined Dockerfile as warning
> Update --verify_only in dockerfiles tool

- structure_tests/README.md
- structure_tests/tests.bzl
> Add a bazel rule definition for structure tests.

- runtime_builders/publish_builders.py
> change json to yaml when publishing legacy latest files

- structure_tests/ext_run.sh
> Update permissions on config files for non-root users.

- structure_tests/BUILD
> add license to structure test bazel build file

- .gitignore
- .travis.yml
- iDiff/cmd/iDiff.go
- iDiff/differs/package.go
- iDiff/utils/diff_utils.go
- iDiff/utils/fs_utils.go
- iDiff/utils/fs_utils_test.go
- iDiff/utils/test_files/dir.json
- iDiff/utils/test_files/dir1/file1
- iDiff/utils/test_files/dir1/file2
- iDiff/utils/test_files/dir1/file3
- iDiff/utils/test_files/dir1_copy/file1
- iDiff/utils/test_files/dir1_copy/file2
- iDiff/utils/test_files/dir1_copy/file3
- iDiff/utils/test_files/dir2/file1
- iDiff/utils/test_files/dir2/file2
- iDiff/utils/test_files/dir2/file4
- iDiff/utils/test_files/dir2_modified/file1
- iDiff/utils/test_files/dir2_modified/file2
- iDiff/utils/test_files/dir2_modified/file4
- iDiff/utils/test_files/dir_bad.json
- iDiff/utils/test_files/file1
- iDiff/utils/test_files/file1_copy
- iDiff/utils/test_files/file2
@nkubala @aaron-prindle @abbytiz
> Preliminary tools for directory diffing for iDiff library

- structure_tests/ext_run.sh
This should fix https://github.com/GoogleCloudPlatform/distroless/issues/65
> Allow structure tests to be run in parallel.

- .gofmt.sh
- vendor/github.com/ghodss/yaml/.gitignore
- vendor/github.com/ghodss/yaml/.travis.yml
- vendor/github.com/ghodss/yaml/LICENSE
- vendor/github.com/ghodss/yaml/README.md
- vendor/github.com/ghodss/yaml/fields.go
- vendor/github.com/ghodss/yaml/yaml.go
- vendor/github.com/ghodss/yaml/yaml_test.go
- vendor/gopkg.in/yaml.v2/LICENSE
- vendor/gopkg.in/yaml.v2/LICENSE.libyaml
- vendor/gopkg.in/yaml.v2/README.md
- vendor/gopkg.in/yaml.v2/apic.go
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/decode_test.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/encode_test.go
- vendor/gopkg.in/yaml.v2/parserc.go
- vendor/gopkg.in/yaml.v2/readerc.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/sorter.go
- vendor/gopkg.in/yaml.v2/suite_test.go
- vendor/gopkg.in/yaml.v2/writerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
- vendor/gopkg.in/yaml.v2/yamlprivateh.go
these were removed by mistake, and are necessary for the structure test code
@dlorenc
> add back vendored yaml packages

- iDiff/utils/tar_utils.go
- iDiff/utils/tar_utils_test.go
- iDiff/utils/testTars/la-croix3-actual.json
- iDiff/utils/testTars/la-croix3-shallow.json
@abbytiz @aaron-prindle @nkubala
> Added deep vs shallow DirToJSON

- iDiff/utils/image_utils.go
@nkubala @aaron-prindle @abbytiz
> Fixing DirToJSON call

- iDiff/differs/aptDiff.go
- iDiff/differs/aptDiff_test.go
Noticed size wasn't being populated, this fixes that issue and adds tests for those cases.
> Fixing apt size parsing and adding tests.

- iDiff/cmd/iDiff.go
- iDiff/differs/aptDiff.go
- iDiff/differs/differs.go
- iDiff/differs/history.go
- iDiff/differs/package.go
- iDiff/utils/format_utils.go
- iDiff/utils/fs_utils.go
- iDiff/utils/package_diff_utils.go
- iDiff/utils/package_diff_utils_test.go
Hist and dir don't currently return JSON's.  I have side-stepped the output formatting so that the apt differ now returns the string version of the JSON for the PackageDiff struct.
> Json output

- iDiff/cmd/iDiff.go
- iDiff/cmd/iDiff_test.go
- iDiff/differs/differs.go
- iDiff/utils/image_utils.go
- iDiff/utils/image_utils_test.go
- iDiff/utils/tar_utils.go
@nkubala @aaron-prindle @abbytiz
> Added image pull from URL functionality

- docgen/lib/render/enhanced.go
- docgen/lib/render/templates/README.md.tmpl
Plus cleaning up of some obsolete TODOs.
> Expose all ports for docker run and docker-compose

- iDiff/differs/aptDiff.go
@nkubala @aaron-prindle @abbytiz
> Fixed output typo

- integration_tests/testsuite/deploy_app.py
> Adding default values for record_latency and language

- iDiff/differs/aptDiff.go
- iDiff/differs/fileDiff.go
- iDiff/differs/nodeDiff.go
- iDiff/differs/pipDiff.go
- iDiff/tests/apt_diff_expected.json
- iDiff/tests/fileDiff_test_processor.py
- iDiff/tests/file_diff_expected.json
- iDiff/tests/multi_version_packages_test_processor.py
- iDiff/tests/node_diff_expected.json
- iDiff/tests/pip_diff_expected.json
- iDiff/utils/format_utils.go
- iDiff/utils/output_templates/fsOutput.txt
- iDiff/utils/output_templates/historyOutput.txt
- iDiff/utils/output_templates/multiVersionOutput.txt
- iDiff/utils/output_templates/singleVersionOutput.txt
#262 @aaron-prindle @nkubala @abbytiz
> Modified human readable output

- iDiff/.iDiffTests.sh
- iDiff/cmd/root.go
- iDiff/tests/apt_diff_expected.json
- iDiff/tests/differ_runs.txt
- iDiff/tests/fileDiff_test_processor.py
- iDiff/tests/file_diff_expected.json
- iDiff/tests/multi_diff_expected.json
- iDiff/tests/multi_version_packages_test_processor.py
- iDiff/tests/node_diff_expected.json
- iDiff/tests/pip_diff_expected.json
- iDiff/tests/preprocess_files.txt
- iDiff/utils/output_utils.go
#268 @aaron-prindle @nkubala @abbytiz
> Fixed output of multiple diffs to follow JSON format

- iDiff/cmd/root.go
- iDiff/main.go
- iDiff/utils/docker_utils.go
- iDiff/utils/image_prep_utils.go
- iDiff/utils/image_utils.go
#267 @aaron-prindle @nkubala @abbytiz
> Adding info log messages

- integration_tests/deploy_check.py
this is leftover from testing.
> remove erroneous sys.exit() call in deploy check

- iDiff/utils/template_utils.go
@aaron-prindle @abbytiz @nkubala
> Fixed tabs in output template

- iDiff/.iDiffTests.sh
@aaron-prindle @abbytiz @nkubala
> Fixed travis test bug

- iDiff/cmd/root.go
#259 @aaron-prindle @nkubala @abbytiz
> Made images prep in parallel

- integration_tests/testsuite/deploy_app.py
this is pretty flaky, so let's retry a few times before exiting with an error.
@dlorenc
> retry when app version delete fails

- integration_tests/requirements.txt
- integration_tests/testsuite/test_logging_custom.py
- integration_tests/testsuite/test_logging_standard.py
See https://github.com/GoogleCloudPlatform/runtimes-common/pull/313 for full explanation.
@dlorenc @tmatsuo
> impose false timeout on logging queries

- WORKSPACE
- structure_tests/tests.bzl
> Add a structure test macro to make test writing easier.

- structure_tests/structure_test.go
- structure_tests/types.go
- structure_tests/types/unversioned/types.go
- structure_tests/types/utils.go
- structure_tests/types/v1/command.go
- structure_tests/types/v1/file_content.go
- structure_tests/types/v1/file_existence.go
- structure_tests/types/v1/licenses.go
- structure_tests/types/v1/structure.go
- structure_tests/types/v2/command.go
- structure_tests/types/v2/file_content.go
- structure_tests/types/v2/file_existence.go
- structure_tests/types/v2/licenses.go
- structure_tests/types/v2/structure.go
- structure_tests/utils/utils.go
> Switch the schema versions to v1 and v2, and use packages.

- structure_tests/types/v2/command.go
- structure_tests/types/v2/structure.go
> change arg names to match k8s pod spec

- reconciletags/BUILD
- reconciletags/config_integrity_test.py
- reconciletags/data_integrity_test.py
> Remove gcloud dependency from tests to package into par files

- integration_tests/README.md
- integration_tests/testsuite/test_custom.py
This extension add support for:
* Tests with multiple steps (requests).
* Configurable requests (headers, method, and content).
* A validation phase (using regular expressions).
Fixes : #289, #288
Note:
The validation endpoints and substitution mechanisms will be added in a separate PR.
> Extension for the Custom Tests in the Integration Framework

- integration_tests/deploy_check.py
This compensates for timing issues with App Engine Flex deployment.
> Add retry logic to deploy_check

- structure_tests/README.md
also, remove deprecated field from test schema
> document drivers in README

- .buildifier.sh
This should unblock https://github.com/GoogleCloudPlatform/runtimes-common/pull/374
cc @aaron-prindle
> Fix buildifier test.

- structure_tests/tests.bzl
cc @nkubala 
I got this working (not sure what the issue was before) and it seems to work for the debian-docker repo. I'll send a PR there after this goes in.
> Switch the structure test bazel rule to use the bazel built binary.

- .buildifier.sh
- .travis.yml
- testing/lib/BUILD
- testing/lib/mock_from_registry.py
- testing/lib/mock_registry.py
- testing/lib/mock_registry_test_base.py
- testing/lib/mock_registry_tests.py
- testing/lib/mock_session_push.py
Basic testing library for mocking FromRegistry and session.Push from the containerregistry library
> Testing library for containerregistry FromRegistry and session.Push

- ftl/node/main.py
This makes it a bit easier to read IMO.
> Stop using some context managers that we don't need.

- structure_tests/README.md
> add docs for metadata tests

- structure_test_cloudbuild.yaml
I'll set up a build trigger to run this on every commit. We can use the retagger to release images to latest.
cc @dlorenc
> update structure test cloudbuild to build and push from build trigger

- structure_tests/drivers/docker_driver.go
- structure_tests/types/v2/structure.go
I moved this into a separate PR so that the structure tests image would be updated, and can then be used for the ftl integration tests.
> structure tests bug

- ftl/ftl_node_integration_tests.yaml
- ftl/node/builder.py
- ftl/node/testdata/packages_lock_test/app.js
- ftl/node/testdata/packages_lock_test/package-lock.json
- ftl/node/testdata/packages_lock_test/package.json
- ftl/node/testdata/packages_lock_test/structure_test.yaml
I expect this to fail, then I'll add a commit to make the new test pass.
> Add an integration test for the package-lock and package.json case.

- integration_tests/testsuite/deploy_app.py
This should prevent us from running into more quota problems with the integration tests.
> Try and cleanup failed deployment before exiting

- ftl/php/benchmark/data/large_app/README.md
- ftl/php/benchmark/data/large_app/composer.json
- ftl/php/benchmark/data/large_app/composer.lock
- ftl/php/benchmark/data/medium_app/README.md
- ftl/php/benchmark/data/medium_app/composer.lock
- ftl/php/benchmark/data/small_app/README.md
- ftl/php/benchmark/data/small_app/composer.json
- ftl/php/benchmark/data/small_app/composer.lock
I couldn't find the original composer.json I used for the small app, so I ended up replacing it with a different one.
> Added README and composer.lock for php benchmarking

- WORKSPACE
- ftl/common/args.py
- ftl/common/builder_runner.py
Also add a flag to specify a different cache repository.
Also I had to bump the PHP base image since this digest appears to have disappeared.
> Make the TTL actually one week.

- versioning/scripts/cloudbuild/main.go
* Add two flags, --enable_parallel and --force_parallel
* Change is backward compatibile
> [cloudbuild] Enable parallel builds

- ftl/common/builder.py
- ftl/common/cache.py
- ftl/common/cache_test.py
- ftl/node/builder.py
- ftl/php/builder.py
- ftl/python/builder.py
This is a small refactor of some of the FTL caching code in preparation for addition of a global cache layer. This has no functional change.
> FTL Cache Refactor

- requirements.txt
> Add PyYAML to requirements

- appengine/reconciletags/BUILD
- appengine/reconciletags/reconciletags_par_test.py
- appengine/reconciletags/retagger.json
- test.sh
> adding special test to make sure reconciletags par file builds correctly

- docgen/README.md
- test.sh
> Add container tools build to test.sh

- ctc_lib/BUILD.bazel
- ctc_lib/CLI_interface.go
- ctc_lib/cli_interface.go
- ctc_lib/container_tool_command.go
- ctc_lib/container_tool_command_base.go
- ctc_lib/container_tool_command_test.go
- ctc_lib/container_tool_list_command.go
- ctc_lib/container_tool_list_command_test.go
- ctc_lib/ctc_lib.go
- ctc_lib/util/util.go
- ctc_lib/version.go
- demo/ctc/cmd/root.go
Depends on PR  #551  and #533 
Review Commit 
https://github.com/GoogleCloudPlatform/runtimes-common/pull/556/commits/814fea1f4d5cc3f25eccd2b9e399591a5f1850a1
> GO CLI Lib Add default Templates. Refactor Execute and define Interface Verified

- versioning/versions/versions.go
Addressing comments from https://github.com/GoogleCloudPlatform/runtimes-common/pull/548 pull requests.
> addressing review commends (Cmd removal and templateArgs tag name)

- ctc_lib/constants/constants.go
- ctc_lib/container_tool_list_command.go
- ctc_lib/container_tool_list_command_test.go
Add StreamO which Executes cobra.Command.Run and streams each item in the List as its added.
Along with that, add Total) function and SummaryTemplate which will display summary at the end of the command.
> Add StreamO for ListCommand

- ctc_lib/container_tool_list_command.go
Fix Summary being printed out Std Err
> Fix Summary being printed out Std Err

- hack/integration_test.go
This should help avoid resource exhausted errors.
> Poll asynchronously.

- ftl/common/builder.py
- ftl/common/cache.py
- ftl/common/cache_test.py
- ftl/common/constants.py
- ftl/common/ftl_util.py
> Set 6 hour TTL for unspecified package deps

- appengine/reconciletags/version_check_test.py
Setting filter to correctly parse go beta versions
> Updating go test to allow for beta versions

- ftl/common/args.py
- ftl/common/builder.py
- ftl/common/cache.py
- ftl/common/cache_test.py
Adds a flag --export-cache-stats to FTL that allows users to instruct FTL to export cache lookup results to output file.
> Adds option to export cache results.

- versioning/scripts/dockerfiles/main.go
Added possibility to create directories for new versions with --add-directories flag
> Added --add-directories flag

- versioning/scripts/dockerfiles/main.go
Renamed add_directory to create_directory
Fixed to only create dirs when flag is passed for backward compatibility
> Renamed flag, fixed default behavior

- versioning/README.md
> Fix a typo
