GoogleCloudPlatform/runtimes-common

check_if_image_tag_exists/cloudbuild.yaml
check_if_image_tag_exists/structure_test.json
structure_tests/Dockerfile
structure_tests/cloudbuild.yaml
structure_tests/run.sh
structure_tests/structure_test.go

This adds code to build an image, gcr.io/gcp-runtimes/structure_test, which serves as an intermediate cloudbuild step to run structure tests against an image before pushing to a registry. The tests use a json file (defaulting to `/workspace/structure_test.json`, though this can be specified through a flag) containing the test definitions to run against the base image.
@dlorenc @selgamal

Structure Test Framework

---

.gitignore
structure_tests/cloudbuild.yaml

Note that you now have to run this from the top level directory, like this:
gcloud alpha container builds create . --config=./structure_tests/cloudbuild.yaml

Fix the cloudbuild.yaml

---

structure_tests/run.sh

need this to support running structure tests on images with non-standard entrypoints.
default entrypoint will be `/bin/sh`; we could also totally remove the entrypoint if you guys think that makes more sense (not all images will contain a shell by default).

allow overriding of base image entrypoint when running structure tests

---

check_if_image_tag_exists/test_config.json
structure_tests/README.md
structure_tests/structure_test.go
structure_tests/types.go

this is necessary, since go's exec.Command() doesn't properly handle joined command strings in all cases (couldn't find a bug for this).
since https://github.com/GoogleCloudPlatform/runtimes-common/pull/28 isn't merged yet, we'll need to manually update this in debian's structure tests to match the current schema version.
once https://github.com/GoogleCloudPlatform/runtimes-common/pull/28 is merged, we'll support legacy space-delimited flag strings (assuming the test writers were able to get their tests to pass with them, which isn't possible in all cases).

change command flags JSON field to array of strings. add verbose logging.

---

structure_tests/ext_run.sh
structure_tests/structure_test.go
structure_tests/types.go

Previously, the "holder" struct contained within the schema map was being reused for multiple config file parse runs; this was causing values from previously parsed config files to stick around inside of test parameters during later test runs, with obviously wonky results. Now, keep a map containing an interface that provides a constructor method, so we can create a new object for each parsing run.

create new StructureTest instance for every file parse to avoid memory overlap

---

structure_tests/ext_run.sh

the original entrypoint was causing the script to fail if the container was started in any directory other than root.
@dlorenc

exit script if any component fails and fix entrypoint

---

check_if_image_tag_exists/structure_test.yaml
structure_tests/README.md
structure_tests/build.sh
structure_tests/cloudbuild.yaml.in
structure_tests/command_test_v1.go
structure_tests/structure_test.go
structure_tests/structure_test_v1.go

~~**UPDATE**: Adding back the flags field. This would cause a few tests to be impossible to run, so I'll leave it as is for now.~~
**UPDATE 2.0, 11/10/16**: Decided we want to rethink env var substitution. For now, hardcoding in $PWD substitution until we figure out how we want to handle the general case. Additionally, unified the way that normal commands and setup/teardown commands are defined in the config and run in the framework.
This adds support for two new fields in the command tests:
* Setup: []string, a list of commands to run before a command test is run. This provides a lot of flexibility for modifying the environment of the test before running the test itself.
* Teardown: []string, a list of commands to run after a test is complete. Exists to allow reversing anything done in …

support for setup/teardown commands in cmd tests

---

structure_tests/ext_run.sh

This will allow test writers to optionally mount a directory at `/workspace` in the test container, to mimic the behavior of a cloudbuild.
Example: 
```
./ext_run.sh -i google/python -c ../../python-runtime/tests/python3-libraries/python3-libraries.yaml -w ../../python-runtime -v
```
@dlorenc

add support for mounting directory as /workspace in test container

---

structure_tests/command_test_v1.go
structure_tests/structure_test_v1.go
structure_tests/types.go

this will add support for setting a list of environment variables inside the image under test. multiple tests have been doing this through creating a new "test image" that inherits from the actual image under test, and running the `ENV` command in the Dockerfile.
additionally, this adds support for specifying a specific expected exit code in a command test. if none is specified, this will default to 0; this will require that test writers are slightly more intentional with their test writing (which I would argue is a good thing).
finally, adds validation for the setup/teardown/envvar fields in the command test struct (without it, a malformed test could cause the framework to panic).
@dlorenc

support setting environment variables and checking specific exit codes in command tests

---

check_if_image_tag_exists/Dockerfile
check_if_image_tag_exists/README.md
check_if_image_tag_exists/main.py
structure_tests/cloudbuild.yaml.in

I realized after doing this that with the addition of the tag reconciler we barely need this tool anymore....but it looked ugly to me so I fixed it. Now instead of passing `python /main.py --image={IMAGE}` you just pass the image name.

fix tag check entrypoint

---

structure_tests/command_test_v1.go
structure_tests/file_content_test_v1.go
structure_tests/file_existence_test_v1.go
structure_tests/licenses_test.go
structure_tests/structure_test_v1.go

missed the fact that this method name would conflict with the `Name` struct field.
@sharifelgamal @dlorenc

change method name to avoid conflict with struct field

---

check_if_image_tag_exists/Dockerfile

Instead of inheriting from a Python base image, the gcloud base image now inherits from Ubuntu and manually installs Python (for all users). This command fails because it doesn't need to be run.
@dlorenc

Remove python symlinking, since it's already done in gcloud base image

---

reconciletags/config_integrity_test.py
reconciletags/data_integrity_test.py

there will be an accompanying change that actually moves these files. this is in preparation for another set of configs for the runtime builders (changing the name to avoid confusion)

move tag config files from .../config to .../tag_config

---

runtime_builders/README.md
runtime_builders/publish_runtime.py

This will be the heart of a job that will monitor the configuration files for the runtime builders, resolve their tags into pinned SHA256 digests and publish them to GCS.
Tests to come.
@sharifelgamal @dlorenc @znewman01

add script to publish runtime-builders to GCS

---

runtime_builders/template_builder.py

this allows us to keep all information related to a project's builder(s) in one location, and to keep all of the configs for each project in one location.
@dlorenc

consolidate config files into single directory

---

runtime_builders/builder_util.py
runtime_builders/data_integrity.py
runtime_builders/publish_builders.py
runtime_builders/template_builder.py

instead of having a list of templated builder files paired up with their associated "tags" (and then making copies of the builder files to those tags), we'll have a single "<runtime>.version" file in GCS that will contain the name of the builder to be used as "latest".
this will remove support for arbitrarily tagging builders, for now. we can add this back in later on once this process is more fleshed out, but removing this will eliminate confusion in the beginning.

switch to using runtime.version file to point to latest builder version

---

reconciletags/latest_age_test.py
reconciletags/reconciletags.py

Changes to reconciletags.py are so when that script is run, the timestamp returned in list-tags is only updated if the latest tag was changed. That's what the new script relies on.

Making sure all deployed images are less than two weeks old.

---

integration_tests/requirements.txt
integration_tests/structure_test.yaml

this should fix an issue with retrieving the client instance in the integration tests

update google-cloud client library dependencies

---

integration_tests/README.md

Loggging, Monitoring, and Exception tests appear to use POST requests as
documented in the descriptions below the titles and in the python
example application.

Fix HTTP methods in documentation for the integration tests.

---

docgen/lib/proto/docgen.proto
docgen/lib/render/enhanced.go

The container name will be derived from the specified run
instruction. Before, the user had to specify a hard-coded name.

Add containerFromRun for exec instruction

---

docgen/WORKSPACE

This is to fix https://github.com/bazelbuild/rules_go/issues/361.

Upgrade to bazel_rules_go 0.4.2

---

integration_tests/README.md
integration_tests/testsuite/driver.py
integration_tests/testsuite/test_custom.py
integration_tests/testsuite/test_exception.py
integration_tests/testsuite/test_logging.py
integration_tests/testsuite/test_logging_custom.py
integration_tests/testsuite/test_logging_standard.py
integration_tests/testsuite/test_monitoring.py
integration_tests/testsuite/test_root.py
integration_tests/testsuite/test_util.py

This PR allows runtime maintainers to run custom integration tests through the standard integration testing framework, by exposing their tests at unused URLs in their sample application. These URLs will be retrieved by the test driver at `/custom`, then poked sequentially by the driver which will be returned the output of each test by the sample application. See the README for more details.
@dlorenc

Add support for running custom tests through integration framework

---

functional_tests/README.md
functional_tests/src/runtest/asserts.go
functional_tests/src/runtest/asserts_test.go
functional_tests/src/runtest/flags.go
functional_tests/src/runtest/main.go
functional_tests/src/runtest/specs.go

Test spec can use `$VAR_NAME`s for variable substitutions. The variable values are passed command line arguments `--vars VAR_NAME=value`, which can appear multiple times to define multiple variables.
Add `matches` in test expectation that accepts a regex.

Add exit code, substitutions, and regex

---

docgen/lib/render/enhanced.go
docgen/lib/render/templates/README.md.tmpl

configmap should be mounted on a directory. Keys in the configmap
will become file names in that directory.

Fix single file mounting for kubernetes

---

runtime_builders/builder_util.py
runtime_builders/data_integrity.py
runtime_builders/publish_builders.py

This is a preliminary attempt at moving the runtime builder "pointers" to live inside of a single manifest file. This file will eventually contain all supported versions of a runtime and the corresponding builder for each; for now, this will just contain all of the `latest` versions in one file.
@markpell @dlorenc

update publish job to write runtime.yaml manifest file

---

check_if_image_tag_exists/cloudbuild.yaml.in
check_if_image_tag_exists/structure_test.yaml
structure_tests/README.md
structure_tests/command_test_v1.go
structure_tests/structure_test_v1.go

alternate take on https://github.com/GoogleCloudPlatform/runtimes-common/pull/138, which will allow people to test intentionally malformed commands on binaries that may or may not exist, with correct error codes.
fixes #74 
@dlorenc

add support for running commands in shell mode

---

structure_tests/run.sh

When we run the docker image, we're already providing all the available
volumes from the structure_test container. This includes /test which
already contains the structure_test binary.
This causes a conflict when you run this build step in parallel with itself. Both images try to write to the same location in /workspace (and the task can fail). An example of this is building 2 images in parallel, each with a structure test after completion.

Skip writing the structure_test binary to /workspace.

---

versioning/scripts/cloudbuild/main.go

The previous loops do not properly group structure tests and functional tests into separate sections.

Fix test ordering

---

runtime_builders/template_builder.py

This allows the job to template tags on strings like "1.1.1=gcr.io/google-appengine/aspnetcore:1.1.1"
@dlorenc @ivannaranjo

account for prefix on images when templating

---

integration_tests/testsuite/deploy_app.py
integration_tests/testsuite/driver.py
integration_tests/testsuite/test_util.py

This will allow us to run multiple integration test runs simultaneously.
@sharifelgamal @dlorenc

Deploy app with version to avoid collisions, and don't stop previous version

---

runtime_builders/publish_builders.py

Using `os.path.join` actually produces erroneous results here, as it puts an extra `/` between the project name and the hyphen separator. SInce this path is only used to retrieve artifacts from GCS (and never anything on the actual host machine), we don't need to care about being platform agnostic, so concatenation should work fine.
Additionally, using substring to retrieve the builder name was hiding this error, so switching to using `str.replace()` as it's cleaner anyway.

Prefer concatenate over os.path.join, and str.replace over substring

---

versioning/scripts/dockerfiles/main.go

Shared files across versions can be put in the templates
directory and they will be distributed to individual version
directories. In the future, we can also support generic .template
files, which are currently not copied; in that case, Dockerfile
will just be a special case.

Copy files from the templates directory

---

integration_tests/testsuite/deploy_app.py

don't direct traffic at this version, since we're deleting it as soon as we're done anyway.
This requires that a placeholder version has already been deployed to the default service, so I'll make sure and have that deployed before running the tests.
@dlorenc

don't promote integration test version when deploying

---

runtime_builders/builder_util.py

This provides a bit of formatting verification before we publish the builder manifest, as per the spec that gcloud expects to find when it reads the file (should not have any GCS-related prefix on the builder file name).
@dlorenc

Verify config formatting before publishing builders

---

integration_tests/README.md
integration_tests/testsuite/deploy_app.py
integration_tests/testsuite/driver.py

This adds support for integration testing the runtime builder images, as part of the gcloud app deploy flow. The sample application will be provided with a templated builder `test.yaml.in` file (as opposed to a templated `Dockerfile.in`), which will have the staging builder image inserted into it, and used as the runtime builder via setting a gcloud config var.
Some runtimes (such as golang) do not even have a base runtime image to integration test, so this is a necessary feature for e2e testing the silver languages.
@dlorenc

Add support for integration testing runtime builder image

---

integration_tests/testsuite/test_logging_custom.py
integration_tests/testsuite/test_logging_standard.py
integration_tests/testsuite/test_util.py

This is a cleaner solution than blacklisting out health check entries, transport errors and other polluting messages. Should fix logging failures in the integration tests.
@dlorenc

Add prefix to log entries for easy search

---

integration_tests/testsuite/test_custom.py
integration_tests/testsuite/test_monitoring.py

Also, slightly increase retry backoff when reading metrics.
@dlorenc

Allow empty response for custom tests from sample app

---

integration_tests/deploy_check.py
integration_tests/requirements.txt
integration_tests/testsuite/deploy_app.py

For #245. This PR is for recording deploy latency data and store it into bigquery table when running deploy check, the data is used for adding a deploy latency metrics to our dashboard.

Record deploy latency data when running deploy check

---

integration_tests/deploy_check.py
integration_tests/testsuite/deploy_app.py

This adds support for testing both flows during the deploy check (if applicable), and recording the latency for each one in a BigQuery table. We can then write some queries to compare the latencies between these for each runtime, and make sure there are no major regressions before switching over to the builder flow.
Fixes #250 
@liyanhui1228 @tmatsuo @dlorenc

Test deployment for both XRT and builder flow during deploy check

---

iDiff/utils/docker_utils.go
iDiff/utils/image_prep_utils.go

Fixes errors produced when calling iDiff on tars and removes some docker dependencies.  #244 
@cftorres @aaron-prindle @nkubala

Removing docker dependency from history calls

---

reconciletags/config_integrity_test.py

This is a temp fix while we wait for #279

increasing the limit of returned images to fix config test

---

structure_tests/ext_run.sh

Before this change, if the user specified an invalid workspace argument, the `readlink` command can fail silently, returning an empty string (try `readlink -f /foo/bar`). This caused the workspace argument check to be missed (because `[ -d ]` returns true), leading to confusing results later in execution.

Structure test ext_run script improvement

---

integration_tests/deploy_check.py

This PR adds an option to the script to skip the XRT flow altogether for those runtimes that do not use the XRT flow, such as the `aspnetcore` runtime.

Adding option to skip the XRT flow when needed.

---

integration_tests/testsuite/test_monitoring.py

Improving integration tests:  
- **increases timeout** to 100 seconds from 80 (see https://github.com/GoogleCloudPlatform/openjdk-runtime/issues/127 for context)
- **attempts to delete the metric** - even if the POST fails (sometimes metrics might get created!) - however the solution is not perfect, as there might be still situations where the metric is created but times out for the test driver, tries and fails to clean it up, and *then* the metric gets created - hence the warning that manual cleanup might be required. (closes #302)
- **improves logging** - when things failed I found these error messages more helpful

integration tests: increasing timeout, improved logging

---

integration_tests/testsuite/test_logging_custom.py
integration_tests/testsuite/test_util.py

Adds the following improvements:
* **project id is taken from google auth** - this works well within a docker container with service accounts and the ``GOOGLE_APPLICATION_CREDENTIALS`` env vars quite well, while the previous ``gcloud``based version doesn't. Let me know if this would break something else 
* **filter** 
* is logged (so it's easy to double check on the UI) and created only once
* adds severity (so that we are testing that too!)
* adds resource as global (well, this is where this might break things) - it's so much faster if you specify a resource as well, it doesn't have to iterate through all the monitored resources to find a matching log name

improvements on custom logging tests

---

docgen/lib/render/templates/README.md.tmpl

* Additional backslash after image name if command is provided (fix)

Docgen: Fix docker compose generation

---

integration_tests/testsuite/test_root.py

this will give the deployed application some time to come up before we try and run the tests. should eliminate some flakiness.
@dlorenc

add retries to root test before running other integration tests

---

integration_tests/testsuite/test_logging_standard.py

Rationale:
We used to use the `test_util.LOGGING_PREFIX` for the filter. It works most of the times, but if we run bunch of integration tests at the same time, the tests may start to fail because the log entry in question might not fit in a single page. We can just safely use the whole token for the filter.

Use the whole token for the filter

---

structure_tests/command_test_v0.go
structure_tests/file_content_test_v0.go
structure_tests/file_existence_test_v0.go
structure_tests/licenses_test_v0.go
structure_tests/structure_test.go
structure_tests/structure_test_v0.go
structure_tests/structure_test_v000.go
structure_tests/structure_test_v1.go
structure_tests/structure_test_v100.go
structure_tests/types.go
structure_tests/utils.go

This adds a new schema version, v1.1.0, which splits the `command` argument in the Command Tests to `entrypoint` and `args`, as expected by k8s configs.
This also contains a bit of refactoring to reflect the version of each test component in the structure test config version.
Partially fixes #317

rename command args to match k8s in schema v1.1.0

---

runtime_builders/data_integrity.py

Since we're deprecating this field anyway, just skip checking it for languages that don't already have it in their config.
@dlorenc

Skip latest check if builder config doesnt have field

---

integration_tests/requirements.txt

Using the old versions caused the integration test build failure.

Update dependency versions

---

.travis.yml
BUILD
WORKSPACE
reconciletags/BUILD
reconciletags/reconciletags.py
reconciletags/reconciletags_e2e_test.py
reconciletags/reconciletags_test.py

This PR updates the WORKSPACE file and creates a BUILD file so that we can use bazel to pull in the containerregistry library, which is used to remove the google3 dependency in retagger (which is 
reconciletags.py)

Remove gcloud dependency from retagger

---

ftl/common/builder.py
ftl/common/cache.py
ftl/common/context.py

They can still be overridden, but don't need to be.
cc @mattmoor

Make the context manager functions consistenly non-abstract.

---

reconciletags/reconciletags.py

Fixes a bug in the retagger which prevented an image in the base registry from being copied into any additional registries

Bug fix in retagger

---

runtime_builders/template_builder.py

Need to preserve the quotes around the cloudbuild args, otherwise we could break gcloud.
cc @tmatsuo

Preserve quotes when reading in builder yamls

---

structure_test_cloudbuild.yaml

This will be run through a build trigger, so that every commit will be built and uploaded to GCS in a folder referenced by commit SHA. We'll have a separate release job for copying selected artifacts into release buckets.
Also planning on updating this build config if/when we update the bazel job to use the `go_build` rule correctly.

add cloudbuild for structure tests

---

ftl/node/builder.py

The test was failing on my machine because npm tries to write to
$HOME/.npm as a cache, and didn't have permissions. This is unlikely
to benefit anything in a container, and will just slow down installs.
cc @aaron-prindle

Add --no-cache to npm install.

---

vendor/github.com/gorilla/mux/BUILD.bazel

I accidentally reverted this in my last godep update. We need a way to make sure this doesn't get changed.

Fix gorilla/mux

---

WORKSPACE
ftl/BUILD
reconciletags/BUILD
structure_tests/BUILD.bazel

I got this to work by running 
```
gcloud components install docker-credential-gcr \
&& docker-credential-gcr configure-docker \
&& bazel run :push_structure_test
```
Might be worth writing a small wrapper script that generates a new bazel build file so we can template in a Docker tag: currently this is publishing to `gcr.io/gcp-runtimes/structure-test:bazel`.
Note this will only work on Linux.
cc @dlorenc

add bazel rules to build and push structure test container image

---

ftl/BUILD
ftl/ftl_node_integration_tests.yaml
ftl/node/main.py
reconciletags/BUILD

Added --image flag so that bazel run can build the image without errors, so that it can be used as a build step in the ftl integration tests.
#413

Update ftl integration tests to use bazel run

---

ftl/node/builder.py
ftl/node/builder_test.py

e.g. 'sh', '-c', 'over-quoted'

Unquote the entrypoint argument.

---

hack/kokoro-test.sh
testing/lib/BUILD

This breaks the remote cache right now, since it has a max size of 512mb.

Switch the mock_registry test to use a smaller image.

---

integration_tests/README.md
integration_tests/deploy_check.py
integration_tests/testsuite/constants.py
integration_tests/testsuite/deploy_app.py
integration_tests/testsuite/driver.py
integration_tests/testsuite/template.py
integration_tests/testsuite/test_custom.py
integration_tests/testsuite/test_exception.py
integration_tests/testsuite/test_logging_custom.py
integration_tests/testsuite/test_logging_standard.py
integration_tests/testsuite/test_monitoring.py
integration_tests/testsuite/test_root.py
integration_tests/testsuite/test_util.py

This PR adds support for automated deploy and testing of sample applications in GKE for all runtimes. It assumes a cluster called `gcp-integration-test-cluster` exists and that we can freely access it (the auth we have set up in the actual jobs should work fine for this). Random image, service, and namespace names are generated by the driver, and substituted into a templated Kubernetes yaml file, which is then used to create the deployment. Tests are then run as normal, and once finished, the created services and namespace are deleted.
~We will need to update the integration test applications to be smarter about their logging sources that they return to the test driver, because they're currently hardcoded to return an App Engine specific source. I'm still working on this for the Python …

Support GKE in Integration Tests

---

integration_tests/testsuite/test_util.py

Using a datetime string caused conflicts for applications that were deployed at the same time, making one of them fail. Random hex strings should avoid conflicts regardless of deploy time.

Randomize version name when deploying app to avoid conflicts

---

integration_tests/deploy_check.py
integration_tests/testsuite/deploy_app.py

also, handle error correctly if the deployment fails so we don't leak deployed versions.

fix writing latency to bigquery in deploy check

---

ftl/integration_tests/ftl_php_integration_tests_yaml.py
ftl/integration_tests/ftl_python_integration_tests_yaml.py
ftl/integration_tests/util.py

I believe this fixes the integration tests.

Remove parallelization within a single cloudbuild for integration tests.

---

ftl/common/ftl_util.py

Name the temporary tar files with a ".tar" suffix to be sure gzip will
compress them.

The 'gzip' binary will not compress files that end in a set of suffixes.

---

ftl/common/builder.py
ftl/common/cache.py
ftl/common/cache_test.py
ftl/node/builder.py
ftl/php/builder.py
ftl/python/builder.py

This PR is an addendum to #493, and should only be merged after #493 has gone in.
This code adds a few more refactors to the caching code, most notably moving the `namespace` and `base_image` fields into the cache `Registry` object. This changes the API for `Get()` and `Set()` to only require the cache key to be passed in.
This should have no functional change.
To make review easier, see this comparison between the latest commit in #493 and this branch: https://github.com/nkubala/runtimes-common/compare/ftl_cache...nkubala:ftl_cache_2
cc @aaron-prindle

more FTL cache refactors

---

ftl/common/args.py
ftl/common/builder.py
ftl/common/cache.py

This code adds a global caching layer in the FTL caching code, that will always be checked first before the local caching layer. Cache misses will be logged in cloudbuild logs, and the code will fall back to checking the local cache before building the layer.
This PR depends on #495, which itself is dependent on #493. They must be merged in order.
The global cache is wrapped in a feature flag, which is turned off by default. Once we settle on a method for populating the global cache, we can enable it.
For ease of review, see this comparison between the latest commit on #495 and the latest commit here: https://github.com/nkubala/runtimes-common/compare/ftl_cache_2...nkubala:global_cache
cc @aaron-prindle @dlorenc

Add FTL global cache

---

ftl/common/args.py
ftl/common/builder.py
ftl/common/builder_test.py
ftl/common/cache.py
ftl/common/constants.py
ftl/common/layer_builder.py
ftl/common/single_layer_image.py
ftl/node/builder.py
ftl/node/builder_test.py
ftl/node/layer_builder.py
ftl/php/builder.py
ftl/php/builder_test.py
ftl/php/layer_builder.py
ftl/python/builder.py
ftl/python/builder_test.py
ftl/python/layer_builder.py

This refactors the FTL code to expose the individual package layer builders, so they can be used outside of a full FTL build. This will be used immediately to populate the global cache, but could also potentially be used in other places where we might need individual package layers.
This should have no functional change.
cc @aaron-prindle @dlorenc

Refactor to expose builders for individual package layers

---

ftl/python/builder.py

- Always log stdout
- Log stderr if it's non-empty
- Raise an exception if the `pip wheel` command exits with a nonzero return code

Display pip stdout and stderr when installing wheels, and check return code

---

ftl/common/builder.py
ftl/common/single_layer_image.py
ftl/python/builder.py

this pr fixes python caching to allow for rebuilding of python images to not have to pip install any packages.  this was done by caching/uploading an image that is the full set of deps from a requirements.txt file

fix python caching

---

ftl/cached/BUILD
ftl/common/builder.py
ftl/common/cache.py
ftl/common/constants.py
ftl/common/ftl_util.py
ftl/common/layer_builder.py
ftl/common/logger.py
ftl/common/single_layer_image.py
ftl/node/builder.py
ftl/node/builder_test.py
ftl/node/layer_builder.py
ftl/node/main.py
ftl/php/builder.py
ftl/php/builder_test.py
ftl/php/layer_builder.py
ftl/php/main.py
ftl/python/builder.py
ftl/python/builder_test.py
ftl/python/layer_builder.py
ftl/python/main.py
test.sh
testing/lib/BUILD
vendor/github.com/ghodss/yaml/BUILD.bazel
vendor/github.com/golang/protobuf/jsonpb/BUILD.bazel
vendor/github.com/golang/protobuf/proto/BUILD.bazel
vendor/github.com/golang/protobuf/ptypes/struct/BUILD.bazel
vendor/gopkg.in/yaml.v2/BUILD.bazel

This code adds logging for all cache gets and sets done by the layer builders when constructing the package layers. This will allow us to track hits and misses, and also track the cache key mappings.
Additionally, this factors out all the logic done by the top-level language builders into the layer builders themselves. The language builders now just drive the high-level assembly of the final images, while the layer builders are responsible for actually installing packages, constructing the layers, and interacting with the cache.

add logging for all cache activity, and move logic to build layers into builders

---

ftl/common/builder.py
ftl/common/cache.py
ftl/common/cache_test.py
ftl/common/single_layer_image.py

No base image is actually used when building the package layers, so we shouldn't be embedding any base image in the keys.
I think (?) this will break any active local caches until the images expire, but I'm not sure this matters much. @aaron-prindle can you confirm

Only compute digest of cache key once, and remove base image from key

---

versioning/versions/versions.go

This functionality will allow to add many custom actions/commands to Dockerfile.templates. Once approved it will obsolute 'Cmd' field from versions.yaml which supports only one command per a given version.

support for many custom commands addded to dockerfiles

---

ftl/common/constants.py
ftl/python/builder.py
ftl/python/builder_test.py
ftl/python/layer_builder.py
ftl/python/testdata/packages_test/structure_test.yaml

fixes the issue where the path for the venv was incorrect in /env/bin/activate as the directory was moved the way it was being built.  now the dir is not moved

fix venv dir path

---

versioning/scripts/cloudbuild/main.go

Usually there is no need to use 32 CPUs and such a VM is very expensive.

Change default machine type from 32CPU to 8CPU.

---

ctc_lib/BUILD.bazel
ctc_lib/cli_interface.go
ctc_lib/container_tool_command.go
ctc_lib/container_tool_command_base.go
ctc_lib/container_tool_list_command.go
ctc_lib/template_test.go
ctc_lib/util/util.go

Also change all cobra.Run to cobra.RunE so any errors when parsing and executing templates are propagated to ctc_lib.Execute() entry point.

Add FuncMap to Templates and validate them

---

.travis.yml

Removing shellcheck from travis until https://github.com/travis-ci/travis-ci/issues/9484 is fixed

Temporarily remove shellcheck from travis

---

ftl/common/logger.py

GCB already puts the timestamps in the log entries, and these make it much harder to aggregate log messages.

remove timestamp from log messages

---

ftl/BUILD
ftl/common/ftl_util.py
ftl/common/logger.py
ftl/common/util_test.py
ftl/node/main.py
ftl/php/main.py
ftl/python/main.py

This couples the log parsing with the FTL common code, so if we change the log formatter we won't have to worry about changing consumer code.

Add util method for parsing log entries

---

ftl/common/builder.py

Our kokoro Int tests have been failing intermittently due to 
""AttributeError: 'module' object has no attribute '_strptime''
This is because datetime.datetime.strptime is not thread safe.
As per the discussions in various thread, (https://mail.python.org/pipermail/python-list/2015-October/697689.html) and more,  the fixes are
1. make an initial call to datetime.datetime.strptime before threading 
2. Another approach is to import _strptime where its called
I am using the first approach which has been successful in other projects.
Example:
https://github.com/boto/boto/pull/1940

Fix for thread unsafe strptime

---

ctc_lib/container_tool_command_base.go
ctc_lib/container_tool_command_test.go

In c-s-t  we are seeing errors https://github.com/GoogleContainerTools//issues/135
```
/bazel-bin/linux_amd64_pure_stripped/container_structure_test  --image gcr.io/google-appengine/debian8 --config tests/debian_failure_test.yaml  -verbose=debug
ERRO[0000] runtime error: invalid memory address or nil pointer dereference 
tejaldesai@tejaldesai~/go/src/github.com/GoogleContainerTools/container-structure-test: (fix_invalid_flags)$ 
```
This is because,  we --image is not a valid arg for root command container_structure_test. The conbra.OnInitialize registered function initLogging is only called when the command is parsed correctly.
Hence, this diff initialize the logging with info log level.

Initialize logging with default info

---

docgen/lib/render/templates/README.md.tmpl

Updating documentation URLs due to Marketplace rebranding.
https://cloud.google.com/launcher/docs/launcher-container would redirect to https://cloud.google.com/marketplace/docs/launcher-container, serving a 404. 
The new URL is https://cloud.google.com/marketplace/docs/marketplace-container

Update documentation URLs

---

appengine/integration_tests/requirements.txt

Otherwise, integration tests fail, because 1.5.4 uses an optional
argument introduced in protobuf 3.6.0:
File "/usr/local/lib/python2.7/dist-packages/google/rpc/code_pb2.py",
line 23, in <module>
serialized_pb=_b('\n\x15google/rpc/code.proto\x12\ngoogle.rpc*\xb7\x02\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\r\n\tCANCELLED\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x12\x14\n\x10INVALID_ARGUMENT\x10\x03\x12\x15\n\x11\x44\x45\x41\x44LINE_EXCEEDED\x10\x04\x12\r\n\tNOT_FOUND\x10\x05\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x06\x12\x15\n\x11PERMISSION_DENIED\x10\x07\x12\x13\n\x0fUNAUTHENTICATED\x10\x10\x12\x16\n\x12RESOURCE_EXHAUSTED\x10\x08\x12\x17\n\x13\x46\x41ILED_PRECONDITION\x10\t\x12\x0b\n\x07\x41\x42ORTED\x10\n\x12\x10\n\x0cOUT_OF_RANGE\x10\x0b\x12\x11\n\rUNIMPLEMENTED\x10\x0c\x12\x0c\n\x08INTERNAL\x1 …

Pin to googleapis-common-protos-1.5.3, as 1.5.4 requires protobuf 3.6.0

---

ftl/php/builder.py

Originally added in #724 as a way of generating a composer-lock.json file server side for users, this change actually pulls all of the deps to do so, voiding the caching benefits of FTL.  This PR undoes the server side file creation done in #724.

remove additional composer update call that was done pre-build for PHP

---

appengine/integration_tests/deploy_check.py

When an error happens when deploying an app or testing the deployed app, `deploy_check.py` logs the error but does not actually return an error code. As a result CI (Kokoro) always reports success even if an error happens. This should fix that issue.

Make deploy_check actually report errors

---

appengine/reconciletags/version_check_test.py

The bug I'm fixing was introduced in #773. 
The file we're parsing for both openjdk and jetty is called java.json, but we need to check them entirely separately, so I reuse the runtime variable to filter on the proper runtime. 
Once we're done checking and aggregate our finding, I want them both back under the "java" heading, so this is just me changing it back.

Make openjdk and jetty show up as the java runtime to clarify output
